on: [push]

jobs:
  slither:
    runs-on: ubuntu-latest
    name: Run slither on the codebase
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Slither
      id: slither
      uses: trailofbits/slither-cloud-action@master
      with:
        slither-cloud-uri: ${{ secrets.SLITHER_CLOUD_URI }}
        truffle-version: 'truffle'
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: "${{ steps.slither.outputs.sarif-path }}"
